### ISSUE TITLE
Find a way to make commit message on origin dynamic

### ISSUE THREAD

**Issue by diomari** [uxdvo/uxdvo-website#1]
Right now we are hard coding "publish" as a commit message every time there's a change on the source code. Find a way to make the commit message dynamic in order to track changes on both origin and upstream repositories.

**Comment by chynnasevilleno** [comment]
Can you elaborate on this more? I'm quite confused :O

**Comment by uxdvo** [comment]
hahaha. @chynnasevilleno right now in order to "publish" or push the code from the `build` folder to the master branch of https://github.com/uxdvo/uxdvo.github.io we add and commit all changes made to this repository `uxdvo-website` pero sa karun naka hardcode lang ang commit message. Anyway usabon lng guro nato ang style sa pag publish. no worries :D

**Comment by uxdvo** [comment]
if you want to check how we deploy our code to the site kindly check `package.json` on line 8

**Comment by uxdvo** [comment]
Closing. resolved on this pr https://github.com/uxdvo/uxdvo-website/pull/3
